// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqFlWzOlPIu7LE4e94C2a2mIWMb318eOM',
    appId: '1:471573751254:web:7a3b941077a27a6518b077',
    messagingSenderId: '471573751254',
    projectId: 'alu-internship-62bc5',
    authDomain: 'alu-internship-62bc5.firebaseapp.com',
    storageBucket: 'alu-internship-62bc5.firebasestorage.app',
    measurementId: 'G-33X17XJYJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMCm-uufQ9X9-uxjVKm0Sv0kS5WlLSyPA',
    appId: '1:471573751254:android:f6f51a9cf3e5c3e418b077',
    messagingSenderId: '471573751254',
    projectId: 'alu-internship-62bc5',
    storageBucket: 'alu-internship-62bc5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfcL8x3HU83R1yYHbjZc7C6AuiC_UGlAA',
    appId: '1:471573751254:ios:3437d460a78280af18b077',
    messagingSenderId: '471573751254',
    projectId: 'alu-internship-62bc5',
    storageBucket: 'alu-internship-62bc5.firebasestorage.app',
    iosBundleId: 'com.example.aluinternship',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfcL8x3HU83R1yYHbjZc7C6AuiC_UGlAA',
    appId: '1:471573751254:ios:3437d460a78280af18b077',
    messagingSenderId: '471573751254',
    projectId: 'alu-internship-62bc5',
    storageBucket: 'alu-internship-62bc5.firebasestorage.app',
    iosBundleId: 'com.example.aluinternship',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqFlWzOlPIu7LE4e94C2a2mIWMb318eOM',
    appId: '1:471573751254:web:79a7633c13f47a2a18b077',
    messagingSenderId: '471573751254',
    projectId: 'alu-internship-62bc5',
    authDomain: 'alu-internship-62bc5.firebaseapp.com',
    storageBucket: 'alu-internship-62bc5.firebasestorage.app',
    measurementId: 'G-9YBEPR4TGB',
  );
}
